### ISSUE TITLE
CidrIp misconfigured in AWS::EC2::SecurityGroup

### ISSUE THREAD

**Issue by dougtreder** [mikehdt/aws-foundry-ssl#3]
The template fails consistently when creating the SecurityGroupIngress*IPv6 resources, because it uses "CidrIp"  for the value "::/0".  This will error will fail the template whether you select static ip or not, and whether or not you've configured the default VPC for IPv6.   

The correct key is "CidrIpv6".

**Comment by mikehdt** [comment]
Aha, I'll check that out when I get a moment. Thanks!

**Comment by mikehdt** [comment]
Okay, this should be fixed now. I also had to split the SSH options into IPv4 and IPv6, which was a fun discovery. I'll close this for now, but please let me know if I missed anything.
